# Generated by Django 4.2.2 on 2023-06-12 07:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alpha', models.SlugField(max_length=3, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('trailer', models.FileField(upload_to='video/trailers/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mkv', 'avi', 'mov', 'webm'])])),
                ('movie', models.FileField(upload_to='video/movies/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mkv', 'avi', 'mov', 'webm'])])),
                ('duration', models.TimeField()),
                ('age_limit', models.SmallIntegerField()),
                ('year', models.DateField()),
                ('language', models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian'), ('en', 'English')], default='uz', max_length=10)),
                ('type', models.CharField(choices=[('free', 'Free'), ('subs', 'Subscription'), ('paid', 'Paid')], default='free', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('job', models.CharField(choices=[('director', 'Director'), ('actor', 'Actor'), ('producer', 'Producer'), ('operator', 'Operator'), ('screenwriter', 'Screen Writer')], default='actor', max_length=20)),
                ('photo', models.ImageField(upload_to='images/persons/')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('biography', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=250, null=True)),
                ('rate', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
